# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clearbit_id', models.CharField(max_length=255, unique=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('site_url', models.CharField(max_length=255)),
                ('linkedin_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('angellist_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
